# Generated by Django 6.0.7 on 2026-08-04 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('users', '0002_remove_userprofile_user_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='departments.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('OFFICER', 'Officer'), ('DEPARTMENT_HEAD', 'Department Head'), ('CITY_ADMIN', 'City Admin'), ('SUPER_ADMIN', 'Super Admin')], default='CITIZEN', max_length=20),
        ),
    ]
