import React, { useState } from 'react';
import {
  Brain,
  Sparkles,
  Check,
  X,
  AlertTriangle,
  ArrowRight,
  Zap,
  TrendingUp,
  MessageSquare,
  ShieldCheck,
  Clock,
  Compass
} from 'lucide-react';

const INITIAL_INSIGHTS = [
  {
    id: 1,
    title: 'Anomalous Complaint Spike',
    description: 'A 280% increase in road pothole reports has been detected near Dharwad within the last 48 hours. Historical data suggests a monsoon wash-out.',
    category: 'Roads & Infrastructure',
    severity: 'High',
    confidence: '94%',
    suggestion: 'Escalate urgency rank, group active complaints, and request immediate allocation of material dispatch to Dharwad maintenance team.',
    status: 'Pending'
  },
  {
    id: 2,
    title: 'Duplicate Complaint Grouping',
    description: '3 newly submitted water leakage complaints in Karwar match description and proximity coordinate patterns of active complaint #CIV-2026-98124.',
    category: 'Water Supply',
    severity: 'Medium',
    confidence: '89%',
    suggestion: 'Merge duplicates into parent complaint #CIV-2026-98124 to avoid redundant dispatch and notify citizens of unified tracking.',
    status: 'Pending'
  },
  {
    id: 3,
    title: 'Automated Routing Optimization',
    description: 'Complaint #CIV-2026-98701 (Garbage dump in park, Shivamogga) was initially routed to Public Parks. Text analysis suggests it should belong to Sanitation.',
    category: 'Sanitation & Waste',
    severity: 'Low',
    confidence: '97%',
    suggestion: 'Approve department re-routing from Public Parks Department to Sanitation & Solid Waste Management division.',
    status: 'Pending'
  },
  {
    id: 4,
    title: 'Predictive Resource Alert',
    description: 'Monsoon forecast trends indicate a highly probable 40% rise in street light outages in Mangaluru. Estimated SLA delay risk is high.',
    category: 'Street Lights',
    severity: 'Medium',
    confidence: '82%',
    suggestion: 'Pre-allocate backup electrical inventory to Mangaluru Municipal warehouse and assign standby field teams.',
    status: 'Applied'
  }
];

const AISuggestions = () => {
  const [insights, setInsights] = useState(INITIAL_INSIGHTS);
  const [toastMessage, setToastMessage] = useState(null);

  const triggerToast = (message) => {
    setToastMessage(message);
    setTimeout(() => setToastMessage(null), 3000);
  };

  const handleAction = (id, newStatus, message) => {
    setInsights(insights.map(item => item.id === id ? { ...item, status: newStatus } : item));
    triggerToast(message);
  };

  return (
    <div className="py-6 space-y-6 animate-in fade-in duration-300">
      
      {/* Toast */}
      {toastMessage && (
        <div className="fixed top-4 right-4 z-50 bg-emerald-600 text-white font-bold px-4 py-3 rounded-xl shadow-xl text-xs">
          {toastMessage}
        </div>
      )}

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-1.5 text-xs font-semibold text-slate-400">
            <span>Home</span>
            <span>&gt;</span>
            <span className="text-slate-600">AI Insights</span>
          </div>
          <h1 className="text-3xl font-black text-slate-900 tracking-tight mt-1.5 flex items-center gap-2">
            <Brain className="text-purple-600" />
            AI Insights & Recommendations
          </h1>
          <p className="text-slate-500 text-sm mt-1">Smart municipal analytics and automated grievance suggestions generated by Civic AI.</p>
        </div>

        <div className="flex items-center gap-3 bg-white border border-slate-200/80 rounded-xl px-4 py-2 shadow-sm text-xs font-bold text-slate-600">
          <Sparkles size={14} className="text-purple-600" />
          <span>System Confidence: 94.5%</span>
        </div>
      </div>

      {/* Stats Cards Row */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-white border border-slate-200/80 rounded-2xl p-5 shadow-sm flex items-center gap-4">
          <div className="p-3 bg-purple-50 text-purple-650 rounded-xl">
            <Brain size={22} />
          </div>
          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Smart Routing</span>
            <span className="text-xl font-black text-slate-900 block mt-0.5">97.8% Accuracy</span>
          </div>
        </div>

        <div className="bg-white border border-slate-200/80 rounded-2xl p-5 shadow-sm flex items-center gap-4">
          <div className="p-3 bg-emerald-50 text-emerald-600 rounded-xl">
            <ShieldCheck size={22} />
          </div>
          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Duplicates Merged</span>
            <span className="text-xl font-black text-slate-900 block mt-0.5">342 Complaints</span>
          </div>
        </div>

        <div className="bg-white border border-slate-200/80 rounded-2xl p-5 shadow-sm flex items-center gap-4">
          <div className="p-3 bg-blue-50 text-blue-600 rounded-xl">
            <Clock size={22} />
          </div>
          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">SLA Reduction</span>
            <span className="text-xl font-black text-slate-900 block mt-0.5">-18.4 Hours Avg</span>
          </div>
        </div>
      </div>

      {/* Recommendations Feed */}
      <div className="space-y-4">
        <h3 className="font-extrabold text-sm text-slate-800 flex items-center gap-2">
          <Zap className="w-4 h-4 text-purple-600 fill-purple-600" />
          Active Recommendations ({insights.filter(i => i.status === 'Pending').length})
        </h3>

        <div className="grid grid-cols-1 gap-4">
          {insights.map((insight) => (
            <div
              key={insight.id}
              className={`bg-white border border-slate-200/80 rounded-2xl p-5 shadow-sm transition-all duration-300 relative overflow-hidden flex flex-col md:flex-row md:items-center justify-between gap-6 ${
                insight.status !== 'Pending' ? 'opacity-60 bg-slate-50/20' : ''
              }`}
            >
              <div className="space-y-3 max-w-3xl">
                <div className="flex flex-wrap items-center gap-3">
                  <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[9px] font-black border ${
                    insight.severity === 'High' 
                      ? 'bg-rose-50 border-rose-100 text-rose-700' 
                      : 'bg-orange-50 border-orange-100 text-orange-700'
                  }`}>
                    {insight.severity} Priority
                  </span>

                  <span className="text-[10px] text-slate-400 font-extrabold uppercase tracking-wider">{insight.category}</span>
                  <span className="text-[10px] text-slate-300 font-bold">•</span>
                  <span className="text-[10px] text-purple-600 font-black flex items-center gap-1"><Sparkles size={10} /> {insight.confidence} match confidence</span>
                </div>

                <div>
                  <h4 className="text-sm font-extrabold text-slate-900">{insight.title}</h4>
                  <p className="text-xs text-slate-500 mt-1 leading-relaxed">{insight.description}</p>
                </div>

                <div className="bg-slate-50 border border-slate-100 p-3 rounded-xl text-xs text-slate-650 flex gap-2">
                  <Brain size={14} className="text-purple-600 shrink-0 mt-0.5" />
                  <p><strong>Proposed Action:</strong> {insight.suggestion}</p>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="shrink-0 flex items-center gap-3 border-t border-slate-100 pt-4 md:border-0 md:pt-0">
                {insight.status === 'Pending' ? (
                  <>
                    <button
                      type="button"
                      onClick={() => handleAction(insight.id, 'Dismissed', 'Suggestion dismissed')}
                      className="p-2.5 border border-slate-200 text-slate-400 hover:text-rose-600 rounded-xl hover:bg-slate-50 transition-colors shadow-sm focus:outline-none"
                      title="Dismiss Suggestion"
                    >
                      <X size={16} />
                    </button>
                    
                    <button
                      type="button"
                      onClick={() => handleAction(insight.id, 'Applied', 'Recommendation applied successfully!')}
                      className="inline-flex items-center gap-1.5 py-2.5 px-4 bg-teal-850 hover:bg-teal-900 text-white rounded-xl text-xs font-bold shadow-md shadow-teal-500/10 transition-all focus:outline-none"
                    >
                      <Check size={14} />
                      Approve AI Suggestion
                    </button>
                  </>
                ) : (
                  <span className={`inline-flex items-center gap-1.5 py-2 px-4 rounded-xl text-xs font-bold border ${
                    insight.status === 'Applied' 
                      ? 'bg-emerald-50 border-emerald-100 text-emerald-700' 
                      : 'bg-slate-100 border-slate-200 text-slate-400'
                  }`}>
                    <Check size={14} />
                    {insight.status}
                  </span>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default AISuggestions;
